/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: Generated<string>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: Generated<string>;
  userId: string;
}

export interface Activity {
  createdAt: Generated<string>;
  eventDate: string;
  eventTimestamp: string;
  eventType: string;
  id: string;
  metadata: string | null;
  organizationId: string;
  repo: string | null;
  title: string | null;
  url: string | null;
  userId: string;
}

export interface ActivitySource {
  config: string | null;
  createdAt: Generated<string>;
  credentials: string;
  id: string;
  isActive: Generated<number>;
  organizationId: string;
  sourceType: string;
  updatedAt: Generated<string>;
  userId: string;
}

export interface Client {
  billingType: string;
  createdAt: Generated<string>;
  freeePartnerId: number | null;
  freeePartnerName: string | null;
  hasWorkDescription: Generated<number>;
  hourlyRate: number | null;
  id: string;
  invoiceNote: string | null;
  invoiceSubjectTemplate: string | null;
  isActive: Generated<number>;
  monthlyFee: number | null;
  name: string;
  organizationId: string;
  paymentTerms: Generated<string>;
  unitLabel: Generated<string | null>;
  updatedAt: Generated<string>;
}

export interface ClientSourceMapping {
  clientId: string;
  createdAt: Generated<string>;
  id: string;
  sourceIdentifier: string;
  sourceType: string;
}

export interface FeatureFlag {
  createdAt: Generated<string>;
  defaultValue: Generated<number>;
  description: string | null;
  id: string;
  key: string;
  updatedAt: Generated<string>;
}

export interface Invitation {
  createdAt: Generated<string>;
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: Generated<string>;
  status: Generated<string>;
  teamId: string | null;
  updatedAt: Generated<string>;
}

export interface Invoice {
  amountExcludingTax: number | null;
  amountTax: number | null;
  billingDate: string | null;
  billingTypeSnapshot: string;
  clientId: string;
  createdAt: Generated<string>;
  freeeInvoiceId: number | null;
  freeeInvoiceNumber: string | null;
  hourlyRateSnapshot: number | null;
  id: string;
  month: number;
  monthlyFeeSnapshot: number | null;
  noteSnapshot: string | null;
  organizationId: string;
  paymentDate: string | null;
  status: string | null;
  subjectSnapshot: string | null;
  totalAmount: number | null;
  year: number;
  yearMonth: string;
}

export interface InvoiceLine {
  description: string | null;
  id: string;
  invoiceId: string;
  quantity: number | null;
  taxRate: number | null;
  unit: string | null;
  unitPrice: number | null;
}

export interface InvoicePdf {
  bytes: number | null;
  createdAt: Generated<string>;
  id: string;
  invoiceId: string;
  kind: string;
  pathOrKey: string;
  sha256: string | null;
  storage: string;
}

export interface Member {
  createdAt: Generated<string>;
  id: string;
  organizationId: string;
  role: Generated<string>;
  updatedAt: Generated<string>;
  userId: string;
}

export interface MonthlyStatus {
  clientId: string;
  id: string;
  organizationId: string;
  sent: Generated<number>;
  updatedAt: Generated<string>;
  yearMonth: string;
}

export interface Organization {
  createdAt: Generated<string>;
  freeeCompanyId: number | null;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string | null;
  updatedAt: Generated<string>;
}

export interface PlaygroundAiUsage {
  createdAt: Generated<string>;
  githubUsername: string | null;
  id: string;
  requestCount: Generated<number>;
  totalInputTokens: Generated<number>;
  totalOutputTokens: Generated<number>;
  updatedAt: Generated<string>;
  userId: string;
  yearMonth: string;
}

export interface ProviderToken {
  accessToken: string | null;
  createdAt: Generated<string>;
  expiresAt: string | null;
  id: string;
  organizationId: string;
  provider: string;
  refreshToken: string | null;
  scope: string | null;
  updatedAt: Generated<string>;
}

export interface Session {
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<string>;
  userAgent: string | null;
  userId: string;
}

export interface Team {
  createdAt: Generated<string>;
  id: string;
  name: string;
  organizationId: string;
  updatedAt: Generated<string>;
}

export interface TeamMember {
  createdAt: Generated<string>;
  id: string;
  teamId: string;
  userId: string;
}

export interface User {
  banExpires: string | null;
  banned: Generated<number | null>;
  banReason: string | null;
  createdAt: Generated<string>;
  email: string;
  emailVerified: Generated<number>;
  id: string;
  image: string | null;
  isAnonymous: Generated<number | null>;
  name: string;
  role: Generated<string | null>;
  updatedAt: Generated<string>;
}

export interface Verification {
  createdAt: Generated<string>;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: Generated<string>;
  value: string;
}

export interface WorkEntry {
  breakMinutes: Generated<number>;
  clientId: string;
  createdAt: Generated<string>;
  description: string | null;
  endTime: string | null;
  hours: number;
  id: string;
  invoiceId: string | null;
  organizationId: string;
  sourceSheet: string | null;
  startTime: string | null;
  userId: string | null;
  workDate: string;
}

export interface DB {
  account: Account;
  activity: Activity;
  activitySource: ActivitySource;
  client: Client;
  clientSourceMapping: ClientSourceMapping;
  featureFlag: FeatureFlag;
  invitation: Invitation;
  invoice: Invoice;
  invoiceLine: InvoiceLine;
  invoicePdf: InvoicePdf;
  member: Member;
  monthlyStatus: MonthlyStatus;
  organization: Organization;
  playgroundAiUsage: PlaygroundAiUsage;
  providerToken: ProviderToken;
  session: Session;
  team: Team;
  teamMember: TeamMember;
  user: User;
  verification: Verification;
  workEntry: WorkEntry;
}
